### ISSUE TITLE
Why is nodename used to connect to remote server?

### ISSUE THREAD

**Issue by odg0318** [Batix/rundeck-ansible-plugin#200]
Hello.

I am using your plugin with Rundeck and I found that `nodename`is used to make a connection instead of `hostname`.

Below line shows what I am saying. 
https://github.com/Batix/rundeck-ansible-plugin/blob/d9fcad02681c6bbc634aa1d18701fbcea4296c08/src/main/java/com/batix/rundeck/plugins/AnsibleNodeExecutor.java#L140

As a document mentions `nodename` is logical identifier and `hostname` is ip address or hostname.
https://rundeck.org/docs/man5/resource-xml.html

What do you think of changing it from `nodename` to `hostname`?
https://rundeck.org/2.10.0/javadoc/index.html?com/dtolabs/rundeck/core/common/INodeEntry.html
```java
jobConf.put(AnsibleDescribable.ANSIBLE_LIMIT,node.getHostname());
```

If you are ok, I will make a PR.

Thanks

**Comment by mcassaniti** [comment]
That should be fine. I've just checked the Ansible Resource Model code and this sets the nodename and hostname properties correctly, so no changes required there. Send through a PR.

@frozenice @DerekTBrown Any objections from you regarding regressions or changes to functionality?

**Comment by frozenice** [comment]
Should be fine. 👍

**Comment by odg0318** [comment]
@mcassaniti I see. If I have any issue, I will reopen this issue. Thanks.
